/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadCrumb: typeof import('./components/AppBreadCrumb.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    SideBarFooter: typeof import('./components/SideBarFooter.vue')['default']
    SideBarHeader: typeof import('./components/SideBarHeader.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
